### ISSUE TITLE
No such var: c/equal?, compiling:(clova/core.cljc:267:7)

### ISSUE THREAD

**Issue by bazo** [markwoodhall/clova#5]
hi, 

i added clova to my project and require it like this

```
(:require [clova.core :refer :all])
```

i think it's ok but i am just a newbie in clojure
anyway, when i run lein run and it starts to compile the app
i get the error in title

Exception in thread "main" java.lang.RuntimeException: No such var: c/equal?, compiling:(clova/core.cljc:267:7)

there's no code using clova yet, so i guess it is a problem in the lib itself.

[clova "0.23.0"] and clojure 1.7.0

**Comment by markwoodhall** [comment]
Hi, if you are using `:refer :all` then you don't need to prefix that `equal?` usage with `c/`. You can simply use `equal?`. If you want to then you can require using `:as c` and use `c/equal?`. 

Hope this makes sense, if not, let me know.

**Comment by bazo** [comment]
the problem is, i'm not using clova anywhere, i just added the require

**Comment by markwoodhall** [comment]
Oh, sorry. I see now, that c/equal? is a call to the clj-time library. Let me check it out, I don't think there are any issues though.

**Comment by markwoodhall** [comment]
I've just created a minimal project to try and reproduce. 

`lein new test`

project.clj

``` clojure
(defproject test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [clova "0.23.0"]])

```

src/test/core.clj

``` clojure
(ns test.core
  (:require [clova.core :refer :all]))

(defn foo
  "I don't do a whole lot."
  [x]
  (println x "Hello, World!"))
```

If I do `lein compile :all` there are no issues. If I do `lein run` there are no issues other than the no :main namespace specified error which we would expect.

What is your project like? Can you provide a simple way to reproduce?

Thanks

**Comment by bazo** [comment]
i could send you the whole project as it does nothing so far or post the relevant files on gist

**Comment by markwoodhall** [comment]
Sure. I'm guessing it will be enough to just gist project.clj and core.clj, if that's ok?

**Comment by bazo** [comment]
there's more files, the app logic is separated in 5 files, maybe it's easier just to change the main namespace and zip it, so you can run it

**Comment by markwoodhall** [comment]
Sure, that works too.

**Comment by bazo** [comment]
you should be able to download it from here http://expirebox.com/download/82af10d2eda1596325fd99de2ae2ec81.html

**Comment by markwoodhall** [comment]
I've just had a quick look. If you run `lein deps :tree` you can see a tree of project dependencies. If you look carefully you will see that `[ring.core "1.4.0"]` overrides to `[clj-time "0.9.0"]`, the `equal?` function was added to `clj-time` in version `0.10.0`. 

You can fix this by adding an exclusion to the `ring.core` dependency. `[ring/ring-core "1.4.0" :exclusions [clj-time]]`, obviously this _could_ cause other issues. If you then run `lein deps :tree` you will see that `clj-time 0.11.0` is used. Running `lein clean` and `lein compile :all` should then work.

**Comment by bazo** [comment]
great, it works now. thanks.

maybe this info should be added to readme file?

**Comment by markwoodhall** [comment]
I'll add a note to the readme but I think this is considered more general clojure dependency management than Clova specific. Thanks for letting me know you had issues, I appreciate it.
